import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import MobileNav from "./_components/Mobilenav";

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk-Light.ttf",
  variable: "--font-space-grotesk",
  weight: "300 500",
});

export const metadata: Metadata = {
  title: "Pbstudios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased bg-[#0E0E0E]`}
      >
        <Navbar/>
        <MobileNav/>
        {children}
      </body>
    </html>
  );
}
