import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import MobileNav from "./_components/Mobilenav";
import Footer from "./_components/Footer";

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk-Light.ttf",
  variable: "--font-space-grotesk",
  weight: "300 500",
});

export const metadata: Metadata = {
  title: "Pbstudios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window !== 'undefined') {
    const tidioScript = document.createElement('script');
    tidioScript.src = '//code.tidio.co/6q1youuxdz26hb3iq8z5qmnix3qhlswh.js'; // Replace with your actual Tidio script code
    tidioScript.async = true;
    document.body.appendChild(tidioScript);
  }
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased bg-[#0E0E0E] text-secondary`}
      >
        <Navbar/>
        <MobileNav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
